# Generated by Django 6.0.6 on 2026-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, help_text="Customer's state — used to determine CGST+SGST vs IGST", max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_state',
            field=models.CharField(blank=True, help_text='Your registered business state, for GST calculation', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hsn_sac_code',
            field=models.CharField(blank=True, help_text='HSN code for goods, SAC code for services', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
