# Generated by Django 6.0.6 on 2026-06-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_state_customuser_business_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='owner', help_text='Owner = full control, Admin = manage data, Member = limited access', max_length=20),
        ),
    ]
