# Generated by Django 6.0.6 on 2026-06-24 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Official company name', max_length=200)),
                ('gstin', models.CharField(blank=True, help_text='Goods and Services Tax Identification Number (15 digits)', max_length=15, null=True)),
                ('pan', models.CharField(blank=True, help_text='Permanent Account Number', max_length=10, null=True)),
                ('address', models.TextField(help_text='Full street address')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(help_text='State/Province name', max_length=100)),
                ('pincode', models.CharField(help_text='Postal code (6 digits for India)', max_length=6)),
                ('phone', models.CharField(help_text='Primary contact number', max_length=15)),
                ('email', models.EmailField(help_text='Primary business email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG, JPG, SVG - max 2MB)', null=True, upload_to='company_logos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='GSTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gst_rate', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=18, help_text='Default GST rate for invoices')),
                ('default_hsn_code', models.CharField(blank=True, help_text='Default Harmonized System of Nomenclature code', max_length=8, null=True)),
                ('default_sac_code', models.CharField(blank=True, help_text='Default Service Accounting Code', max_length=6, null=True)),
                ('is_registered', models.BooleanField(default=True, help_text='Is company registered under GST?')),
                ('composition_scheme', models.BooleanField(default=False, help_text='Is company under composition scheme?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Settings',
                'verbose_name_plural': 'GST Settings',
            },
        ),
        migrations.CreateModel(
            name='InvoiceBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(choices=[('#0066cc', 'Blue'), ('#1a1a1a', 'Dark Gray'), ('#27ae60', 'Green'), ('#e74c3c', 'Red'), ('#f39c12', 'Orange'), ('#9b59b6', 'Purple'), ('#3498db', 'Light Blue'), ('#2ecc71', 'Light Green')], default='#0066cc', help_text='Primary color for invoice header and accents', max_length=7)),
                ('secondary_color', models.CharField(default='#f5f7fa', help_text='Secondary color for invoice background', max_length=7)),
                ('invoice_title', models.CharField(default='INVOICE', help_text='Title shown in invoice', max_length=50)),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text for invoices', null=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms & conditions text for invoices', null=True)),
                ('signature_text', models.CharField(blank=True, help_text="Signature/authorization text (e.g., 'Authorized By')", max_length=200, null=True)),
                ('signature_image', models.ImageField(blank=True, help_text='Digital signature image', null=True, upload_to='signatures/%Y/%m/')),
                ('show_hsn_sac', models.BooleanField(default=True, help_text='Show HSN/SAC codes in invoice items')),
                ('show_tax_breakdown', models.BooleanField(default=True, help_text='Show CGST/SGST/IGST breakdown')),
                ('show_notes', models.BooleanField(default=True, help_text='Show notes section in invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Branding',
                'verbose_name_plural': 'Invoice Branding',
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('update', 'Updated'), ('create', 'Created'), ('delete', 'Deleted')], max_length=20)),
                ('model_name', models.CharField(help_text='Model that was changed', max_length=50)),
                ('field_changed', models.CharField(help_text='Field that was changed', max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(help_text='SMTP server address (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port (typically 587 for TLS, 465 for SSL)')),
                ('smtp_username', models.CharField(help_text='SMTP username or email address', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP password (encrypted)', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (usually for port 465)')),
                ('from_email', models.EmailField(help_text='From email address for outgoing emails', max_length=254)),
                ('from_name', models.CharField(help_text='From name for outgoing emails', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable SMTP configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile/phone number', max_length=15, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio or designation', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/%Y/%m/')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='Timezone for user', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी'), ('kn', 'ಕನ್ನಡ')], default='en', help_text='Preferred language', max_length=10)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('invoice_reminders', models.BooleanField(default=True, help_text='Receive invoice payment reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile Settings',
                'verbose_name_plural': 'User Profile Settings',
            },
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ac_user_id_3418de_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='accounts_ac_action_fde492_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', '-created_at'], name='accounts_cu_user_id_1b58cc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='accounts_cu_email_cc1dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='accounts_in_user_id_5019f3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='accounts_in_invoice_72c085_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='accounts_in_status_08f461_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='accounts_no_is_read_d448a6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', '-created_at'], name='accounts_su_user_id_c26358_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='accounts_su_status_065a97_idx'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicebranding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_branding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofilesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
        migrations.AddIndex(
            model_name='settingsauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_se_user_id_a7132f_idx'),
        ),
    ]
