# Generated by Django 6.0.6 on 2026-06-27 07:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_invoiceitem_payment_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoiceitem',
            new_name='accounts_in_payment_3da4bd_idx',
            old_name='accounts_in_payment_idx',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
