# Generated by Django 6.0.6 on 2026-06-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_accounts_in_payment_idx_accounts_in_payment_3da4bd_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_is_read_d448a6_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL to navigate to when clicked', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(default='info', help_text='Bootstrap color (success, danger, warning, info, primary)', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='info-circle', help_text='Bootstrap icon name (e.g., "bell", "envelope", "check-circle")', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_deleted', 'Invoice Deleted'), ('invoice_paid', 'Invoice Paid'), ('invoice_pending', 'Invoice Pending'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('customer_added', 'Customer Added'), ('customer_updated', 'Customer Updated'), ('customer_deleted', 'Customer Deleted'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert'), ('backup_created', 'Backup Created'), ('backup_failed', 'Backup Failed'), ('renewal_due', 'Renewal Due'), ('renewal_expired', 'Renewal Expired'), ('subscription_renewed', 'Subscription Renewed'), ('system_info', 'Information'), ('system_success', 'Success'), ('system_warning', 'Warning'), ('system_error', 'Error')], default='system_info', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_model',
            field=models.CharField(blank=True, help_text='Model name (e.g., "Invoice", "Customer", "Product")', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, help_text='UUID or ID of the related object', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-created_at'], name='accounts_no_is_read_78f484_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='accounts_no_priorit_f708f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='accounts_no_notific_6d2f3e_idx'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
