# Generated by Django 6.0.6 on 2026-06-29 05:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_create_notification_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('renewal_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('trial', 'Trial')], default='manual', max_length=20)),
                ('renewed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_expiry', models.DateTimeField(blank=True, null=True)),
                ('new_expiry', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='paid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-renewed_on'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subscription',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.invoice'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('grace', 'Grace Period')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['renewal_status', 'expires_at'], name='accounts_su_renewal_0365d3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active'], name='accounts_su_user_id_a90e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'renewal_status'], name='accounts_su_custome_241cf1_idx'),
        ),
        migrations.AddField(
            model_name='renewalhistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='renewalhistory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.invoice'),
        ),
        migrations.AddField(
            model_name='renewalhistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to='accounts.subscription'),
        ),
        migrations.AddField(
            model_name='renewalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='renewalhistory',
            index=models.Index(fields=['subscription', '-renewed_on'], name='accounts_re_subscri_5dbb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='renewalhistory',
            index=models.Index(fields=['user', '-renewed_on'], name='accounts_re_user_id_297597_idx'),
        ),
    ]
