# Generated by Django 6.0.6 on 2026-07-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_subscription_renewal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_14_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_30_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_7_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
