# Generated by Django 6.0.6 on 2026-06-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backups_bac_user_em_e09842_idx',
            old_name='backups_user_model_date_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backups_bac_backup__29fb67_idx',
            old_name='backups_type_date_idx',
        ),
    ]
